### ISSUE TITLE
Handling graceful shutdown

### ISSUE THREAD

**Issue by Chuwiey** [StreetContxt/kcl-akka-stream#19] opened 2019-03-03 16:03 UTC
I'm running to an issue dealing with a graceful shutdown. It seems on the kinesis side I have two workers trying to consume from the same shard which triggers a graceful shutdown request. That's all handled well, but the actor system never dies, and the workers don't come back up, so I'm left with an actor system that just sits there once the source dies.

Is there a way to catch the shutdown request and re-init the worker or source? looking at the code:
https://github.com/StreetContxt/kcl-akka-stream/blob/master/src/main/scala/com/contxt/kinesis/KinesisSource.scala#L109

It seems that when a shutdown occurs, there's no restarting of the worker?

**Comment by anikifoss** [comment] 2019-03-03 23:07
`KinesisSource` should terminate with an error when the worker is shutdown before the stream. To check if that is the case, you can obtain the stream termination future using `Flow.watchTermination()` method as follows:

```
val streamTerminationFuture = KinesisSource(kclConfig, sourceConfig)
  .watchTermination()(Keep.right)
  .runWith(Sink.ignore)
```

To recover a failed source, you can use `Source.recoverWithRetries()`.

**************************************************

Alternatively `KinesisSource` has a materialized value of type `Future[Done]` which completes on Kinesis worker shutdown. Unlike the stream termination future, the worker termination future should complete without an error if the worker was shutdown gracefully.

You can use either the stream termination future or the worker termination future to restart your source as follows:
```
def restartForever(): Unit = {
  val workerTerminatedFuture = KinesisSource(kclConfig, sourceConfig)
    .runWith(Sink.ignore)

  workerTerminatedFuture.onComplete { 
    case Success(_) =>
      log.error("Restarting worker after graceful shutdown.")
      restartForever()
      
    case Failure(e) =>
      log.error("Restarting worker after shutdown with error.", e)
      restartForever()
  }
}
restartForever()
```

**Comment by anikifoss** [comment] 2019-05-16 01:25
@Chuwiey were you able to resolve your issue?

**Comment by AnumSheraz** [comment] 2020-01-27 13:43
thanks @lexn82 for the possible workaround to this issue. But in our case, we're seeing this log 
`Restarting worker after graceful shutdown.` quite often (once a minute). I have 20 shards and 10 workers (with different IDs). Here is the log of one of the worker (showing only one shutdown event log);

```
13:44:20.433 [RecordProcessor-0001] INFO com.contxt.kinesis.RecordProcessorImpl - Successfully checkpointed ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000018) at Offset(sequenceNumber=49603570280835199426883763222579325060907211244831768866, subSequenceNumber=214).
13:44:20.433 [RecordProcessor-0001] INFO com.contxt.kinesis.RecordProcessorImpl - Finished shutting down ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000018), reason: REQUESTED.
13:44:20.434 [RecordProcessor-0000] INFO com.contxt.kinesis.RecordProcessorImpl - Successfully checkpointed ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000015) at Offset(sequenceNumber=49603605574819678193790145091321097359040551291535229170, subSequenceNumber=56).
13:44:20.434 [RecordProcessor-0000] INFO com.contxt.kinesis.RecordProcessorImpl - Finished shutting down ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000015), reason: REQUESTED.
Jan 27, 2020 1:44:20 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker shutdown
INFO: Worker shutdown requested.
Jan 27, 2020 1:44:20 PM com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator stop
INFO: Worker 6463ca76-504b-414c-a2f4-b32658d5c760 has successfully stopped lease-tracking threads
13:44:21.426 [RecordProcessor-0001] INFO com.contxt.kinesis.RecordProcessorImpl - Finished shutting down ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000018), reason: ZOMBIE.
13:44:21.426 [RecordProcessor-0000] INFO com.contxt.kinesis.RecordProcessorImpl - Finished shutting down ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000015), reason: ZOMBIE.
Jan 27, 2020 1:44:21 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.GracefulShutdownCoordinator$GracefulShutdownCallable waitForRecordProcessors
INFO: Waiting for 2 record processors to complete final shutdown
13:44:22.426 [scala-execution-context-global-634] INFO Main - Restarting worker after graceful shutdown.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker createClient
WARNING: Received configuration for region as us-east-1.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker createClient
WARNING: Received configuration for region as us-east-1.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker createClient
WARNING: Received configuration for region as us-east-1.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator <init>
INFO: With failover time 10000 ms and epsilon 25 ms, LeaseCoordinator will renew leases every 3308 ms, takeleases every 20050 ms, process maximum of 2147483647 leases and steal 1 lease(s) at a time.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker <init>
INFO: Shard sync strategy determined as SHARD_END.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Initialization attempt 1
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Initializing LeaseCoordinator
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Syncing Kinesis shard info
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Starting LeaseCoordinator
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.leases.impl.LeaseRenewer initialize
INFO:  Worker 6463ca76-504b-414c-a2f4-b32658d5c760 found lease {
  "leaseKey" : "shardId-000000000018",
  "leaseOwner" : "6463ca76-504b-414c-a2f4-b32658d5c760",
  "leaseCounter" : 5829,
  "concurrencyToken" : null,
  "lastCounterIncrementNanos" : null,
  "checkpoint" : {
    "sequenceNumber" : "49603570280835199426883763222579325060907211244831768866",
    "subSequenceNumber" : 214
  },
  "pendingCheckpoint" : null,
  "ownerSwitchesSinceCheckpoint" : 0,
  "parentShardIds" : [ ]
}
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.metrics.impl.MetricsHelper getMetricsScope
WARNING: No metrics scope set in thread {prefix}_0068, getMetricsScope returning NullMetricsScope.
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.leases.impl.LeaseRenewer initialize
INFO:  Worker 6463ca76-504b-414c-a2f4-b32658d5c760 found lease {
  "leaseKey" : "shardId-000000000015",
  "leaseOwner" : "6463ca76-504b-414c-a2f4-b32658d5c760",
  "leaseCounter" : 5771,
  "concurrencyToken" : null,
  "lastCounterIncrementNanos" : null,
  "checkpoint" : {
    "sequenceNumber" : "49603605574819678193790145091321097359040551291535229170",
    "subSequenceNumber" : 56
  },
  "pendingCheckpoint" : null,
  "ownerSwitchesSinceCheckpoint" : 0,
  "parentShardIds" : [ ]
}
Jan 27, 2020 1:44:22 PM com.amazonaws.services.kinesis.metrics.impl.MetricsHelper getMetricsScope
WARNING: No metrics scope set in thread {prefix}_0068, getMetricsScope returning NullMetricsScope.
Jan 27, 2020 1:44:23 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker shouldShutdown
INFO: All record processors have been shutdown successfully.
Jan 27, 2020 1:44:23 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker finalShutdown
INFO: Starting worker's final shutdown.
Jan 27, 2020 1:44:23 PM com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable shutdown
INFO: Shutting down CWPublication thread.
Jan 27, 2020 1:44:23 PM com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable run
INFO: CWPublication thread finished.
Jan 27, 2020 1:44:23 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker run
INFO: Worker loop is complete. Exiting from worker.
Jan 27, 2020 1:44:32 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker run
INFO: Initialization complete. Starting worker loop.
Jan 27, 2020 1:44:32 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker infoForce
INFO: Created new shardConsumer for : ShardInfo [shardId=shardId-000000000018, concurrencyToken=104823d8-a4b1-45b6-b741-ba548c143046, parentShardIds=[], checkpoint={SequenceNumber: 49603570280835199426883763222579325060907211244831768866,SubsequenceNumber: 214}]
Jan 27, 2020 1:44:32 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockOnParentShardTask call
INFO: No need to block on parents [] of shard shardId-000000000018
Jan 27, 2020 1:44:32 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker infoForce
INFO: Created new shardConsumer for : ShardInfo [shardId=shardId-000000000015, concurrencyToken=d7f51c92-62ba-452d-93d2-8d8283e85b6b, parentShardIds=[], checkpoint={SequenceNumber: 49603605574819678193790145091321097359040551291535229170,SubsequenceNumber: 56}]
Jan 27, 2020 1:44:32 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockOnParentShardTask call
INFO: No need to block on parents [] of shard shardId-000000000015
Jan 27, 2020 1:44:33 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher initialize
INFO: Initializing shard shardId-000000000018 with 49603570280835199426883763222579325060907211244831768866
Jan 27, 2020 1:44:33 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher initialize
INFO: Initializing shard shardId-000000000015 with 49603605574819678193790145091321097359040551291535229170
13:44:33.563 [RecordProcessor-0001] INFO com.contxt.kinesis.RecordProcessorImpl - Starting ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000015) at Offset(sequenceNumber=49603605574819678193790145091321097359040551291535229170, subSequenceNumber=56).
13:44:33.567 [RecordProcessor-0000] INFO com.contxt.kinesis.RecordProcessorImpl - Starting ShardConsumerId(us-east-1,prod-stream,TestAkkaStream,shardId-000000000018) at Offset(sequenceNumber=49603570280835199426883763222579325060907211244831768866, subSequenceNumber=214).
```
So here are my two questions;
1. do we have an idea of why the worker gets request to be shutdowned, and if so, why is it so often?
```I have a feeling that the worker gets gracefully shutdown as soon as reads all available lease from shard ? ```
Looking at DynamoDB table, it seems like no two workers are reading from same shard, but I cannot be 100% sure on that. 

2. is there any drawback of following the `restartForever()` approach ?

**Comment by anikifoss** [comment] 2020-01-29 21:02
I'm not sure why the workers would start shutting down. Maybe there were internal Kinesis service changes related to the Kinesis Client 2.0 update, so the older client versions are no longer working quiet as well.

**Comment by anikifoss** [comment] 2020-01-29 21:41
@AnumSheraz To answer your second question: there are no downside to restarting the stream, as long as all the resources are cleaned up correctly. However, there will be some additional latency as the stream is restarting, and possibly more latency due to workers reshuffling the load among themselves. So it's better to fix the root cause of the unexpected worker shutdowns. Hopefully the patch by @trucnguyenlam upgrading to KCL v2 will help with that.

**Comment by AnumSheraz** [comment] 2020-01-30 03:57
I can confirm that @trucnguyenlam patch works amazingly well as expected, without workers restarting. And is much faster then @ukayani's patch, where he is using blocking approach on checking for checkpoints.

**Comment by angelo-streetcontxt** [comment] 2020-04-22 16:17
As we've now merged and released the patch, I'm going to close out this issue. If you have further issues please feel free to re-open.

**Closed as completed by angelo-streetcontxt** 2020-04-22 16:17 UTC
